### ISSUE TITLE
"error = 'openapi' not found in provider's services configuration"

### ISSUE THREAD

**Issue by jbarnes7952** [dikhan/terraform-provider-openapi#62] opened 2018-10-06 20:33 UTC
## Describe the bug
Attempting to run `plan` against sample goa environment.

A clear and concise description on how does it work now and what's the current behaviour.

1. make local-env
2. export PROVIDER_NAME=goa && curl -fsSL https://raw.githubusercontent.com/dikhan/terraform-provider-openapi/master/scripts/install.sh | bash -s -- --provider-name $PROVIDER_NAME
3. create main.tf using example
4. terraform init && terraform plan  

I also had to set the url using the terraform-provider-openapi.yaml as setting the `OTF_VAR_goa_SWAGGER_URL` env variable had no e ffect and only errored saying the `OTF_VAR_goa_SWAGGER_URL` wasn't set.

## Expected behaviour
A completed plan without error.

## Additional context
```
2018-10-06T20:29:14.448Z [DEBUG] plugin: starting plugin: path=/home/vagrant/.terraform.d/plugins/terraform-provider-goa args=[/home/va
grant/.terraform.d/plugins/terraform-provider-goa]
2018-10-06T20:29:14.451Z [DEBUG] plugin: waiting for RPC address: path=/home/vagrant/.terraform.d/plugins/terraform-provider-goa
2018-10-06T20:29:14.542Z [DEBUG] plugin.terraform-provider-goa: plugin address: timestamp=2018-10-06T20:29:14.541Z network=unix address
=/tmp/plugin059454931
2018-10-06T20:29:14.543Z [DEBUG] plugin.terraform-provider-goa: 2018/10/06 20:29:14 [INFO] found open api plugin configuration at /home/vagrant/.terraform.d/plugins/terraform-provider-openapi.yaml
2018-10-06T20:29:14.544Z [DEBUG] plugin.terraform-provider-goa: 2018/10/06 20:29:14 [ERROR] There was an error initialising the terraform provider: plugin init error: error occurred when getting service configuration from plugin configuration file terraform-provider-ope
napi.yaml - error = 'openapi' not found in provider's services configuration
2018/10/06 20:29:14 [ERROR] root: eval: *terraform.EvalInitProvider, err: unexpected EOF
2018/10/06 20:29:14 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/10/06 20:29:14 [TRACE] [walkInput] Exiting eval tree: provider.goa
2018/10/06 20:29:14 [TRACE] dag/walk: upstream errored, not walking "goa_bottles.my_bottle"
2018/10/06 20:29:14 [TRACE] dag/walk: upstream errored, not walking "provider.goa (close)"
2018/10/06 20:29:14 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/10/06 20:29:14 [TRACE] dag/walk: upstream errored, not walking "root"

2018/10/06 20:29:14 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-10-06T20:29:14.547Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
Error: Error asking for user input: 1 error(s) occurred:

* provider.goa: unexpected EOF

```

**Comment by dikhan** [comment] 2018-10-06 21:44
Hi @jbarnes7952,

Thanks for raising the ticket. The error seems to suggest that your terraform config file (main.tf) contains a provider called openapi. 


error = 'openapi' not found in provider's services configuration

Can you check if that’s the case? 

If you are using env variables when calling terraform, pls make sure you also add the OTF_INSECURE_SKIP_VERIFY="true" before invoking terraform. The example API’s use a self sign cert and if the flag is not set the http go client used within the openapi provider will error when valisatong the cert. adding the insecure verify will make the http client ignore the validation.

Let me know if this helps.

Dani

**Comment by dikhan** [comment] 2018-10-06 21:53
Actually, the OTF_INSECURE_SKIP_VERIFY="true" only applies to beckends using https like the swagfercodegen example, but goa example foes not use https so that should not be an issue.

**Comment by jbarnes7952** [comment] 2018-10-07 03:42
My main.tf

```
$ cat main.tf 
resource "goa_bottles" "my_bottle" {
  name = "Name of bottle"
  rating = 3
  vintage = 2653
}
```

```
$ cat terraform-provider-openapi.yaml 
version: '1'
services:
    goa: 
      swagger-url: http://127.0.0.1:9090/swagger/swagger.yaml
```

I'm simply running the examples, I haven't added "openapi" to anything.  

The VM has latest docker, docker-compose, golang & terraform:

```
vagrant@ubuntu-xenial:~$ docker --version
Docker version 18.06.1-ce, build e68fc7a
vagrant@ubuntu-xenial:~$ docker-compose --version
docker-compose version 1.22.0, build f46880fe
vagrant@ubuntu-xenial:~$ go version
go version go1.11.1 linux/amd64
vagrant@ubuntu-xenial:~$ ./terraform version
Terraform v0.11.8
+ provider.goa (unversioned)
```

VM Provisioning:

```
    echo PROVIDER_NAME=goa >> /home/vagrant/.bashrc
    echo Cloning repo..
    su -c "git clone https://github.com/dikhan/terraform-provider-openapi" vagrant
    echo Make local-env.. 
    su -c "export PATH=$PATH:/usr/local/go/bin && cd terraform-provider-openapi && make local-env" vagrant
    echo Provider install script..
    su -c "cd terraform-provider-openapi/scripts && ./install.sh --provider-name goa" vagrant
```

local-env is up:
```
vagrant@ubuntu-xenial:~$ docker ps
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS                                         NAMES
93aabb3a382e        swaggercodegen-service-provider-api:latest   "./cdn-service-provi…"   8 minutes ago       Up 8 minutes        0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   swaggercodegen-service-provider-api
6fc077ad4608        goa-service-provider-api:latest              "./goa-service-provi…"   8 minutes ago       Up 8 minutes        0.0.0.0:9090->9090/tcp                        goa-service-provider-api
54246fb23cd3        swaggerapi/swagger-ui:latest                 "sh /usr/share/nginx…"   8 minutes ago       Up 8 minutes        80/tcp, 0.0.0.0:8082->8080/tcp                swagger-ui-swaggercodegen
```

All looks good until:

```
vagrant@ubuntu-xenial:~$ ./terraform plan

Error: Error asking for user input: 1 error(s) occurred:

* provider.goa: unexpected EOF
```

Hopefully I'm just missing a step here, I'm really interested to see this operational.  

Thanks
-J

**Comment by jbarnes7952** [comment] 2018-10-07 03:43
[tf_log.txt](https://github.com/dikhan/terraform-provider-openapi/files/2453611/tf_log.txt)

**Comment by dikhan** [comment] 2018-10-07 16:43
Hi @jbarnes7952,

The above info helped a lot, thanks. I think I know what the issue is and it's related to the way the os.Executable() function works. Based on the documentation:

````
// Executable returns the path name for the executable that started
// the current process. There is no guarantee that the path is still
// pointing to the correct executable. If a symlink was used to start
// the process, depending on the operating system, the result might
// be the symlink or the path it pointed to. If a stable result is
// needed, path/filepath.EvalSymlinks might help.
````

The provider uses this function to learn about the name of the provider and based on that configure itself appropriately with either the env variables (OTF_VAR_<providerName>_SWAGGER_URL) or the plugin config file (terraform-provider-openapi.yaml).

Depending on the environment you are running the open api provider, the os.Executable() function might return the symlink name or the executable it's pointing to, in your case terraform-provider-openapi instead of terraform-provider-goa ...I am working on a fix for this and hopefully I will be able to get it pushed and merged shortly (today/tomorrow).

In the meantime and to make sure I can reproduce your issue, can I ask you to share you Vagrantfile pls?

In the meantime, to get you unblocked...you can follow the [manual provisioning steps](https://github.com/dikhan/terraform-provider-openapi#openapi-terraform-provider-manual-installation) (not using symlinks, just renaming the downloaded binary with your providers name, e,g: terraform-provider-goa) instead of using the install script. 

Thanks,
Dani

**Comment by dikhan** [comment] 2018-10-07 23:33
Hi @jbarnes7952,

Just pushed a released that should solve the problems with symlinks...the install.sh script no longer creates a symlink referencing the openapi provider so if you check the terraform plugin installation folder you should be able to see seomthing like:

````
root@f6adcf6fe316:/openapi# ls -la ~/.terraform.d/plugins/
total 35036
drwxr-xr-x 1 root root      4096 Oct  7 23:26 .
drwxr-xr-x 1 root root      4096 Oct  7 23:26 ..
-rwxr-xr-x 1  501 staff 17930688 Oct  7 23:11 terraform-provider-goa
-rw-r--r-- 1 root root       240 Oct  7 23:09 terraform-provider-openapi.yaml

cat  ~/.terraform.d/plugins/terraform-provider-openapi.yaml
version: '1'
services:
  goa:
    swagger-url: http://goa-service-provider-api.com:9090/swagger/swagger.yamlroot@f6adcf6fe316:/openapi# 
````

I have added a new target to the make file that brings up the example APIs as well as a container initialized with terraform and the OpenAPI providers (similar to your vagrant env):

````
$ make examples-container
````

Updated the example [docs](https://github.com/dikhan/terraform-provider-openapi#examples) with more info about this example environment.

Let me know if the problem still persist or you have any questions.

Thanks,
Dani

**Comment by jbarnes7952** [comment] 2018-10-09 00:11
Hey @dikhan 

Awesome. the examples seem to be working in the new build using the `make examples-container`.  

Thanks!
-J

**Comment by dikhan** [comment] 2018-10-09 00:41
Cool, thx for confirming. Will go ahead and close this ticket then.

Thanks,
Dani

**Closed by dikhan** 2018-10-09 00:41 UTC

**Comment by dikhan** [comment] 2018-11-17 16:55
Hi @jbarnes7952 , wondering how's the usage of the OpenAPI provider coming along? Looking for some feedback :)

Thanks!
Dani
