### ISSUE TITLE
subdocuments: parent_id is required in all arrays elements

### ISSUE THREAD

**Issue by fredericosilva** [dikhan/terraform-provider-openapi#181] opened 2019-11-07 17:42 UTC
## Describe the bug
parent_id is required in all arrays elements of the subdocument

## To Reproduce

Using the following swagger spec

```yml
swagger: '2.0'
paths:
  "/zone":
    post:
      description: ''
      parameters:
      - in: body
        name: body
        required: true
        schema:
          "$ref": "#/definitions/zone"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/zone"
  "/zone/{zone_id}":
    get:
      description: ''
      parameters:
      - in: path
        name: zone_id
        required: true
        type: string
      responses:
        '200':
          schema:
            "$ref": "#/definitions/zone"
  "/zone/{zone_id}/recordset":
    get:
      responses:
        '200':
          description: OK
          schema:
            items:
              "$ref": "#/definitions/zone_recordset"
            type: array
    post:
      description: ''
      parameters:
      - in: path
        name: zone2_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          "$ref": "#/definitions/zone_recordset"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/zone_recordset"
  "/zone/{zone_id}/recordset/{id}":
    get:
      description: ''
      parameters:
      - in: path
        name: zone_id
        required: true
        type: string
      - in: path
        name: id
        required: true
        type: string
      responses:
        '200':
          schema:
            "$ref": "#/definitions/zone_recordset"

definitions:
  zone:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
  zone_recordset:
    type: object
    properties:
      id:
        type: string
        readOnly: true
      zone_id:
        type: string
        readOnly: true
      record:
        type: array
        items:
          type: object
          properties:
            content:
              type: string
```

Terraform

```tf
resource "demo_zone" "test" {
    name = "test.com"
}

resource "demo_zone_recordset" "test" {
    zone_id = "${demo_zone.test.id}"

    record {
        # parent_id is required in all subdocuments arrays
        # zone_id = "${demo_zone.test.id}"
        content = "test"
    }
}
```

Terraform plan

```
$ terraform plan

Error Missing required argument

  on main.tf line 8, in resource "demo_zone_recordset" "test":
  8:     record {

The argument "zone_id" is required, but no definition was found.
```

## Expected behaviour
parent_id shouldn't be required.

### Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

**Comment by dikhan** [comment] 2019-11-08 07:21
Hi @fredericosilva , thanks for opening the issue. We will prioritize the bug in the backlog accordingly. First glance looks like an easy bug so might be able to put a fix soon. Always happy to collaborate too so if you would like to take a stub at it here’s a [link](https://github.com/dikhan/terraform-provider-openapi/blob/master/openapi/openapi_v2_resource.go#L353) to the code that injects the parent id in the subresource schema on the fly. As you mentioned, the bug is reproducible when a given resource has not only primitive properties in the definition but also arrays of objects and a unit test with that schema configuration should be easy to put in place to document the bug and then add the corresponding implementation fix.

**Comment by fredericosilva** [comment] 2019-11-09 20:29
@dikhan Thank you for pointing me in the right direction. How would you approach the problem? Is there a simple way to detect that case or the Schema needs to be enriched?

**Comment by dikhan** [comment] 2019-11-09 21:17
Hi @fredericosilva , just pushed a potential fix for this issue. After having been able to reproduce the issue via a unit test I realized that the source of the issue was the code responsible for building the schema of the resource was being used recursively to build not only the first level set of properties in the resource schema but also deeper levels when handling 'complex' properties like objects and arrays of objects. The code in charge of building the schema, had logic to also inject the parent id if the endpoints was a sub-resource, and the missing bit was that the recursive calls were also applying the same logic. I did a little refactoring to only include the parent properties in the first level (https://github.com/dikhan/terraform-provider-openapi/pull/182/files#diff-b681f6e002691f2f904d8c19b36268f5R332) and ignore them in other deeper levels (https://github.com/dikhan/terraform-provider-openapi/pull/182/files#diff-b681f6e002691f2f904d8c19b36268f5R336).

Please take a look at [PR-182](https://github.com/dikhan/terraform-provider-openapi/pull/182) and see if the issue is now solved. Looking forward to your feedback.

Dani

**Comment by fredericosilva** [comment] 2019-11-10 09:39
Hello,

Just tried that PR, it does fix it.

```tf
Terraform will perform the following actions:

  # openapi_zone.test will be created
  + resource "openapi_zone" "test" {
      + id   = (known after apply)
      + name = "test.com"
    }

  # openapi_zone_recordset.test will be created
  + resource "openapi_zone_recordset" "test" {
      + id      = (known after apply)
      + zone_id = (known after apply)

      + record {
          + content = "test"
        }
    }
```

Thank you!

**Comment by fredericosilva** [comment] 2019-11-10 10:33
Terraform refresh fails later on

```
Error: record: '': source data must be an array or slice, got struct
```

Going to try isolate the problem

**Comment by fredericosilva** [comment] 2019-11-10 12:05
@dikhan the problem seems to in convertPayloadToLocalStateDataValue so I guess is not specific to subdocuments, do you want me to open a new issue?

**Comment by dikhan** [comment] 2019-11-10 18:02
> Terraform refresh fails later on
> 
> ```
> Error: record: '': source data must be an array or slice, got struct
> ```
> 
> Running with TF_LOG=TRACE
> 
> ```
> ...
> 2019-11-10T12:22:55.418+0100 [DEBUG] plugin.terraform-provider-openapi: 2019/11/10 12:22:55 [DEBUG] GET 'zone_recordset' response payload: map[string]interface {}{"id":"5dc7ea784a73dff1721fcad6", "name":"test4.test2.com.", "record":[]interface {}{map[string]interface {}{"content":"1.2.3.4", "enabled":true}}, "ttl":60, "type":"A"}
> 2019-11-10T12:22:55.418+0100 [DEBUG] plugin.terraform-provider-openapi: 2019/11/10 12:22:55 [DEBUG] found array type property 'record' with items of type 'object'
> 2019-11-10T12:22:55.419+0100 [DEBUG] plugin.terraform-provider-openapi: 2019/11/10 12:22:55 [DEBUG] found array type property 'record' with items of type 'object'
> 2019/11/10 12:22:55 [ERROR] <root>: eval: *terraform.EvalRefresh, err: record: '': source data must be an array or slice, got struct
> 2019/11/10 12:22:55 [ERROR] <root>: eval: *terraform.EvalSequence, err: record: '': source data must be an array or slice, got struct
> ...
> ```
> 
> Going to try isolate the problem

Hi @fredericosilva , taking a look at the response sent by the API and the openapi schema definition of the `zone_recordset` object, they do not seem to match. As per the API response, the `record` property seems to contain: 
- An object containing `content` and `enabled` properties
- A int property ttl
- A string property type

Pasting here the reply from the API as per your debug log:

````
map[string]interface {}{
"id":"5dc7ea784a73dff1721fcad6", 
"name":"test4.test2.com.", 
"record":[]interface {}{
     map[string]interface {}{
        "content":"1.2.3.4", 
        "enabled":true}
     }, 
     "ttl":60, 
     "type":"A"
}
````

Whereas the openapi definition is defined as follows:
````
  zone_recordset:
    type: object
    properties:
      id:
        type: string
        readOnly: true
      zone_id:
        type: string
        readOnly: true
      record:
        type: array
        items:
          type: object
          properties:
            content:
              type: string
````

Please go ahead and create another issue if needed. Perhaps updating the openapi spec to reflect the API behaviour might fix the issue.

**Comment by fredericosilva** [comment] 2019-11-11 20:20
I assumed that extra properties would be ignored. I was wrong. Maybe we can add a more more verbose error. All seems to be fine now.

Thank you :)

**Closed** 2019-11-12 19:00 UTC
Labels: bug, good first issue

**Comment by dikhan** [comment] 2019-11-12 20:21
@fredericosilva fyi - merged the PR that introduced a fix for that (https://github.com/dikhan/terraform-provider-openapi/pull/182) and pushed a new released (https://github.com/dikhan/terraform-provider-openapi/releases/tag/v0.22.3).

As far as the extra properties is concerned, the openapi plugin can help surfacing issues related to miss-match between API documentation and API  behaviour so the service owner can fix the discrepancies. Basically it uses the OpenAPI document as the API contract.

Agreed on the output being a bit more user friendly. What would you propose?

**Comment by fredericosilva** [comment] 2019-11-13 12:33
Looking back, I think it should not error.
Right now extra properties in the root object are ignored when they are not defined, I think we should have the same behaviour for the array objects. Going to open a new issue.

**Comment by dikhan** [comment] 2019-11-13 18:16
Hi @fredericosilva I think these are different use cases. 

- When there are extra properties not specified in the openapi spec, as you mentioned the plugin ignores them when updating the state file.
- When the API comes back with data types that do not match the documented types, the plugin fails. This is expected as the casting can not be done.

So correct me if I am wrong, but the issue you are referring to is when the array is populated ok, meaning the items are homogenous but some of the properties in the object are not documented. If this is the issue you are referring to I also think it's worth capturing into an issue and also reproducing it.

Please let me know if I missed something.

Thanks,
Dani

**Comment by fredericosilva** [comment] 2019-11-13 20:25
@dikhan you are correct

using the previous example

```yaml
  zone_recordset:
    type: object
    properties:
      id:
        type: string
        readOnly: true
      record:
        type: array
        items:
          type: object
          properties:
            content:
              type: string
```

with the following reply from the api
```json
{
    "id": "5dc7ea784a73dff1721fcad6",
    "name": "test4.test2.com.",
    "record": {
        "content": "1.2.3.4",
        "enabled": true
    },
    "ttl": 60,
    "type": "A"
}
```

I would expect it to ignore `record.enabled` property and log
```
2019-11-13T21:16:27.305+0100 [DEBUG] plugin.terraform-provider-openapi: 2019/11/13 21:16:27 [WARN] The API returned a property that is not specified in the resource's schema definition in the OpenAPI document - error = property with name 'enabled' not existing in resource schema definition
```
As far as I remember that logic is recursive, so it should be a bit harder to have the full property path. `enabled` vs `record.enabled`

instead is errors with
```
Error: record: '': source data must be an array or slice, got struct
```

What do you think?
